# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphviz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrowvisual',
            name='modifier',
            field=models.CharField(choices=[('l', 'left'), ('r', 'right'), ('o', 'non-filled')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='arrowvisual',
            name='shape',
            field=models.CharField(choices=[('box', 'box'), ('crow', 'crow'), ('diamond', 'diamond'), ('dot', 'dot'), ('inv', 'inv'), ('none', 'none'), ('normal', 'normal'), ('tee', 'tee'), ('vee', 'vee')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='cacheimage',
            name='file',
            field=models.ImageField(upload_to='graph_images'),
        ),
        migrations.AlterField(
            model_name='nodevisual',
            name='options',
            field=models.CharField(blank=True, help_text='comma-separated options', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodevisual',
            name='shape',
            field=models.CharField(choices=[('box', 'Box'), ('circle', 'Circle'), ('doublecircle', 'Double circle'), ('box3d', 'Box 3D'), ('diamond', 'Diamond'), ('parallelogram', 'Parallelogram')], default='circle', max_length=50),
        ),
    ]
